apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot
          image: acrchatbotm3.azurecr.io/chatbot-poc:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          env:
            - name: MISTRAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chatbot-secret
                  key: MISTRAL_API_KEY
            - name: STREAMLIT_SERVER_PORT
              value: "8501"
            - name: STREAMLIT_SERVER_ADDRESS
              value: "0.0.0.0"
          readinessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot
spec:
  type: LoadBalancer
  selector:
    app: chatbot
  ports:
    - port: 80
      targetPort: 8501
